[global]
  workgroup = WORKGROUP
  security = user
  server string = Samba Quadlet
  server role = standalone server
  map to guest = never
  server min protocol = SMB3
  disable netbios = yes
  smb encrypt = desired
  server multi channel support = yes

[nas]
  path = /tank/nas
  browsable = yes
  read only = no
  guest ok = no
  create mask = 0644
  directory mask = 2775
  force user = root
