#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # established/related traffic
        ct state established,related accept

        # all loopback traffic
        iifname "lo" accept

        # ping request
        icmp type echo-request accept

        # SSH from anywhere
        tcp dport 22 accept

        # DNS
        tcp dport 53 accept
        udp dport 53 accept

        # DHCP
        udp dport 67 accept

        # Plex
        tcp dport 32400 accept

        # Traefik
        tcp dport {443, 3128, 8080} accept

        # samba
        tcp dport 445 accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}
