arch: amd64
cores: 2
features: nesting=1
hostname: podman.local.technoplaza.net
memory: 2048
nameserver: 192.168.1.2
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=BC:24:11:D6:4B:B3,ip=192.168.1.3/24,type=veth
ostype: debian
rootfs: local-zfs:subvol-100-disk-0,size=32G
searchdomain: local.technoplaza.net
swap: 0
unprivileged: 1
