arch: amd64
cores: 2
features: nesting=1
hostname: podman.local.technoplaza.net
memory: 2048
nameserver: 192.168.1.2
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=BC:24:11:D6:4B:B3,ip=192.168.1.3/24,type=veth
ostype: debian
rootfs: local-zfs:subvol-100-disk-0,size=32G
searchdomain: local.technoplaza.net
swap: 0
unprivileged: 1
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
## SAMBA CHANGES
# new ID map to allow uid 1000 on pve in lxc container
lxc.idmap: u 0 100000 1000
lxc.idmap: g 0 100000 1000
lxc.idmap: u 1000 1000 1
lxc.idmap: g 1000 1000 1
lxc.idmap: u 1001 101001 198999
lxc.idmap: g 1001 101001 198999
# mount NAS directory from proxmox->lxc
mp0: /tank/nas,mp=/tank/nas

## PLEX CHANGES
# mount plex config directory from proxmox->lxc
mp1: /tank/plex,mp=/tank/plex
# allow /dev/dri/renderD* for hardware transcoding
lxc.cgroup2.devices.allow: c 226:* rwm
lxc.mount.entry: /dev/dri dev/dri none bind,create=dir
